import {
  headerValue,
  type CaptureBundle,
  type CaptureEntry,
  type HeaderPair,
} from '@omniproxy/schema';
import { analyzeBundle, type AnalysisResult, type AnalyzedStep, type ValueLink } from './analyze.js';

/**
 * Turning an analyzed capture into a `provider.yaml` draft.
 *
 * This is the last piece of the onboarding conveyor (§8): record, sanitize, analyze,
 * **draft**. It is also the piece where honesty is easiest to lose, so the rules are
 * strict and the output is loud about them.
 *
 * **It writes down only what it saw.** Every endpoint, header and path in the draft
 * came out of the recording. Where the recording is silent the draft says so with a
 * `# TODO(capture):` comment instead of a plausible guess — a guessed value is
 * indistinguishable from a recorded one three weeks later, and that is how a
 * declaration ends up lying about a provider (§12.1).
 *
 * **The draft is a draft.** It comes out with `status: needs-capture` and a header
 * saying what a human still has to decide. Nobody should be able to run
 * `omniproxy provider draft` and ship the result without reading it.
 *
 * The output is text, not an object, and it is assembled by hand rather than through
 * a YAML serializer. That is deliberate: comments are most of the value here, and no
 * serializer keeps them where they belong.
 */

export interface DraftOptions {
  /** Provider id for the declaration. Defaults to the bundle's. */
  providerId?: string;
  displayName?: string;
  /** Path to the sanitized fixture, recorded in the `capture` block. */
  fixturePath?: string;
}

export interface DraftResult {
  yaml: string;
  /** What the human has to settle before this can be used. */
  todos: string[];
  /** What was inferred and might be wrong. */
  notes: string[];
  analysis: AnalysisResult;
}

export function draftDeclaration(bundle: CaptureBundle, options: DraftOptions = {}): DraftResult {
  const analysis = analyzeBundle(bundle);
  const id = options.providerId ?? bundle.providerId;
  const todos: string[] = [];
  const notes: string[] = [];

  const base = commonBase(analysis.flow);
  if (!base) {
    todos.push(
      'the recording spans several hosts, so there is no single channel base — split ' +
        'it into one provider per host, or set allowedHosts by hand',
    );
  }

  const send = analysis.flow.find((step) => step.classification === 'send');
  const session = analysis.flow.find((step) => step.classification === 'session');
  const stream = analysis.flow.find((step) => step.classification === 'stream');

  // The analyzer names a call `send` when it POSTs and streams back. A provider that
  // answers in one body never gets that label, so fall back to the last request whose
  // body carries a prompt-shaped field. That is still evidence — the key name is in
  // the recording — and without it a one-shot provider drafts to nothing at all.
  const inferred =
    send === undefined && stream === undefined
      ? inferSendStep(analysis.flow, bundle.entries)
      : undefined;
  if (inferred) {
    notes.push(
      `no call in this recording streams, so the request to ${inferred.url} was taken as ` +
        'the send because its body carries a prompt-shaped field. Check that.',
    );
  }

  const sendStep = send ?? stream ?? inferred;
  if (!sendStep) {
    todos.push(
      'no request in this capture looks like the one that carries the prompt — record ' +
        'a scenario where you actually send a message',
    );
  }
  const lines: string[] = [];

  /* ─────────────────────────────── the header ─────────────────────────────── */

  lines.push(
    '# Draft generated by `omniproxy provider draft`. NOT ready to use.',
    '#',
    '# Everything below came out of a recording — no endpoint, header or path here was',
    '# invented. What the recording could not answer is marked `TODO(capture)` rather',
    '# than filled in with something plausible, because a guess and a fact look the',
    '# same three weeks later.',
    '#',
    `# Recorded: ${bundle.capturedAt} (${bundle.method}, scenario: ${bundle.scenario})`,
    `# Entries: ${bundle.entries.length} — ${analysis.flow.length} in the flow, ${analysis.noise.length} set aside`,
    '',
    'schemaVersion: 1',
    `id: ${id}`,
  );
  if (options.displayName) lines.push(`displayName: ${quote(options.displayName)}`);
  lines.push(
    '# needs-capture until a human has read this file and tried it. Raising the status',
    '# is a decision, not a side effect of generating a draft.',
    'status: needs-capture',
    '',
    'capture:',
  );
  if (options.fixturePath) lines.push(`  bundle: ${quote(options.fixturePath)}`);
  lines.push(
    `  capturedAt: ${bundle.capturedAt.slice(0, 10)}`,
    `  method: ${bundle.method}`,
    `  coverage: [${bundle.scenario}]`,
    '',
  );

  /* ─────────────────────────────── the channel ─────────────────────────────── */

  const headers = sendStep ? staticHeaders(bundle.entries, analysis.flow) : [];

  lines.push('channels:', '  - id: web', '    kind: web-http');
  if (base) {
    lines.push(`    base: ${quote(base)}`);
  } else {
    lines.push('    # TODO(capture): several hosts were recorded, so there is no single base.');
    lines.push(`    base: ${quote(firstOrigin(analysis.flow) ?? 'https://TODO.example')}`);
  }
  lines.push('    fingerprint:');
  lines.push('      # A profile name, not a position on a scale. Which one this provider');
  lines.push('      # needs is decided by trying it, not by reading the capture.');
  lines.push('      profile: node-undici');
  lines.push('      impersonate: false');

  if (sendStep) {
    const order = headerOrderOf(bundle.entries, sendStep.index);
    if (order.length > 0) {
      lines.push(`      headerOrder: [${order.join(', ')}]`);
    }
  }

  if (headers.length > 0) {
    lines.push('      static:');
    for (const [name, value] of headers) lines.push(`        ${name}: ${quote(value)}`);
    notes.push(
      `${headers.length} header(s) were identical on every recorded request and are ` +
        'treated as static. Any of them that is really per-request belongs in the step.',
    );
  }
  lines.push('');

  /* ──────────────────────────────── the auth ──────────────────────────────── */

  const auth = authShape(bundle.entries);
  lines.push('auth:', `  kind: ${auth.kind}`);
  if (auth.kind === 'none') {
    lines.push('  # No credential-shaped header was recorded. If this provider does need');
    lines.push('  # one, the recording was of a logged-out session — record again.');
  }
  lines.push('  present:', '    headers:');
  for (const [name, template] of auth.headers) lines.push(`      ${name}: ${quote(template)}`);
  if (auth.headers.length === 0) lines.push('      {}');
  lines.push('');

  /* ──────────────────────────────── the flow ──────────────────────────────── */

  lines.push('flow:');

  // Calls the analyzer could not name, made before the send. Dropping them would be
  // the worst failure this generator could have: the draft would look complete and
  // the provider would answer 403, because the step that mints the token is missing.
  const prepare = sendStep
    ? analysis.flow.filter(
        (step) =>
          step.classification === 'unknown' &&
          step.index < sendStep.index &&
          step.index !== session?.index,
      )
    : [];

  if (prepare.length > 0) {
    lines.push('  prepare:');
    for (const step of prepare) {
      lines.push(`    # TODO(capture): what is this call for? It ran before the send and`);
      lines.push(`    #   could not be classified, so it is kept rather than dropped. If`);
      lines.push(`    #   its response feeds a computed header, that is a transform.`);
      const block = requestBlock(bundle.entries[step.index], base, 6);
      lines.push(`    -${block[0]?.slice(5) ?? ''}`);
      lines.push(...block.slice(1));
      lines.push('      # extract: { name: $.path.to.value }');
    }
    lines.push('');
    notes.push(
      `${prepare.length} call(s) before the send could not be classified and are kept as ` +
        'prepare steps. Look at them: an unexplained call is usually anti-bot work.',
    );
  }

  if (session) {
    lines.push('  createSession:');
    lines.push("    unless: '{{state.sessionId}}'");
    lines.push(...requestBlock(bundle.entries[session.index], base, 4));
    const produced = session.produces[0];
    if (produced) {
      lines.push('    extract:');
      lines.push(`      sessionId: ${jsonPathFor(produced)}`);
      lines.push('    persist:');
      lines.push("      sessionId: '{{extracted.sessionId}}'");
      notes.push(
        `the session id was traced from ${produced.sourcePath} into ${produced.targetPath} ` +
          'of a later request — that link is why this step is here at all.',
      );
    } else {
      lines.push('    # TODO(capture): nothing from this response was reused later, so');
      lines.push('    #   what to extract is a guess. Check the response by hand.');
    }
    lines.push('');
  }

  if (sendStep) {
    const entry = bundle.entries[sendStep.index];
    lines.push('  send:');
    lines.push(...requestBlock(entry, base, 4, session !== undefined));
    lines.push(...streamBlock(entry));
    lines.push('');
  }

  /* ─────────────────────────────── the rest ─────────────────────────────── */

  lines.push(
    'errors:',
    '  # TODO(capture): a successful recording contains no failures, so there is nothing',
    '  #   here to learn error shapes from. Record a session that hits the message limit',
    '  #   and one with an expired login, then add the rules those reveal.',
    '  - match: { status: 401 }',
    '    as: auth_expired',
    '    retryable: no',
    '  - match: { status: 429 }',
    '    as: rate_limit',
    '    retryable: other-account',
    '',
    'models:',
    '  # TODO(capture): one recording shows one model. Names come from the provider,',
    '  #   usually from a list endpoint or the model picker in its UI.',
    `  - alias: ${id}-default`,
    `    native: ${modelHint(bundle) ?? quote('TODO-the-model-name-this-provider-expects')}`,
    '',
    'context:',
    '  strategy: flatten-to-prompt',
    '  # No `measured` block: the context budget has to be measured, and a number here',
    '  # without a measurement is a guess wearing a fact\'s clothes.',
    '',
    'probe:',
    '  interval: 30m',
    '  request:',
    '    prompt: Reply with the single word OK.',
    '  expect:',
    '    contains: OK',
  );

  todos.push(
    'read every TODO(capture) comment in the file',
    'try it: omniproxy capture record ' + id + ' --auth <file.json>',
    'raise status only once it has actually answered',
  );

  for (const warning of analysis.warnings) notes.push(warning);

  return { yaml: `${lines.join('\n')}\n`, todos, notes, analysis };
}

/* ─────────────────────────────────── internals ─────────────────────────────────── */

function requestBlock(
  entry: CaptureEntry | undefined,
  base: string | undefined,
  indent: number,
  hasSession = false,
): string[] {
  const pad = ' '.repeat(indent);
  if (!entry) return [`${pad}# TODO(capture): no request recorded for this step`];

  const url = safeUrl(entry.request.url);
  const path = url ? url.pathname : entry.request.url;
  const lines = [`${pad}request:`, `${pad}  method: ${entry.request.method.toUpperCase()}`];

  lines.push(`${pad}  path: ${quote(base ? path : entry.request.url)}`);

  if (url && url.search) {
    lines.push(`${pad}  query:`);
    for (const [name, value] of url.searchParams) {
      lines.push(`${pad}    ${name}: ${quote(templatise(value, hasSession))}`);
    }
  }

  const perRequest = perRequestHeaders(entry.request.headers);
  if (perRequest.length > 0) {
    lines.push(`${pad}  headers:`);
    for (const [name, value] of perRequest) {
      // Never the recorded value. A signature, a nonce or a proof-of-work blob is
      // computed per request and expires; writing the one we saw produces a header
      // that looks authoritative and 403s forever. It has to become a transform, and
      // choosing which transform is a decision only a person can make (ADR-0002).
      lines.push(`${pad}    # TODO(capture): this header changed per request. It needs a`);
      lines.push(`${pad}    #   transform under \`vars:\`, not a constant. Recorded shape:`);
      lines.push(`${pad}    #   ${describeValue(value)}`);
      lines.push(`${pad}    ${name}: '{{vars.TODO}}'`);
    }
  }

  if (entry.request.body !== undefined && entry.request.body !== '') {
    lines.push(...bodyBlock(entry.request.body, pad, hasSession));
  }

  return lines;
}

/**
 * The recorded body, with the values we can recognise replaced by placeholders.
 *
 * Only two substitutions are made, and both are ones the analyzer proved: a value that
 * was traced from an earlier response becomes `{{state.sessionId}}`, and the prompt
 * text becomes `{{req.prompt}}`. Everything else is left exactly as recorded, even
 * where it looks like it ought to be dynamic. Guessing wrongly here produces a
 * declaration that sends a literal where a value belongs, and that failure surfaces as
 * a generic 400 from the provider hours later.
 */
function bodyBlock(body: string, pad: string, hasSession: boolean): string[] {
  let parsed: unknown;
  try {
    parsed = JSON.parse(body);
  } catch {
    return [
      `${pad}  # TODO(capture): the recorded body was not JSON. It is reproduced verbatim;`,
      `${pad}  #   replace the parts that change per request with {{...}} placeholders.`,
      `${pad}  body: ${quote(body.slice(0, 500))}`,
    ];
  }

  if (parsed === null || typeof parsed !== 'object' || Array.isArray(parsed)) {
    return [`${pad}  json: ${JSON.stringify(parsed)}`];
  }

  const fields = Object.entries(parsed as Record<string, unknown>);
  if (fields.length === 0) return [`${pad}  json: {}`];

  const lines = [`${pad}  json:`];
  for (const [key, value] of fields) {
    lines.push(`${pad}    ${key}: ${yamlScalar(value, key, hasSession)}`);
  }
  return lines;
}

function yamlScalar(value: unknown, key: string, hasSession: boolean): string {
  if (typeof value === 'string') {
    if (isPromptKey(key)) return quote('{{req.prompt}}');
    if (hasSession && isSessionKey(key)) return quote('{{state.sessionId}}');
    return quote(value);
  }
  if (value === null) {
    // A recorded null on a parent-message field is the first turn of a conversation,
    // not a constant. `null-if-empty` is the form that keeps both cases working.
    return isParentKey(key) ? quote('{{state.parentMessageId|null-if-empty}}') : 'null';
  }
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  return JSON.stringify(value);
}

function isPromptKey(key: string): boolean {
  return ['prompt', 'message', 'text', 'query', 'input', 'content'].includes(key.toLowerCase());
}

function isSessionKey(key: string): boolean {
  const lower = key.toLowerCase();
  return lower.includes('session') || lower === 'chat_id' || lower === 'conversation_id';
}

function isParentKey(key: string): boolean {
  const lower = key.toLowerCase();
  return lower.includes('parent') || lower === 'previous_message_id';
}

function templatise(value: string, hasSession: boolean): string {
  return hasSession && /^[0-9a-f-]{8,}$/i.test(value) ? '{{state.sessionId}}' : value;
}

/** The stream block, decided by what the response actually looked like. */
function streamBlock(entry: CaptureEntry | undefined): string[] {
  if (!entry) return [];
  const frames = entry.response.frames ?? [];
  const mime = (entry.response.mimeType ?? '').toLowerCase();

  if (frames.length === 0 && !mime.includes('event-stream')) {
    return [
      '    # The recorded response was one body, not a stream.',
      '    response:',
      '      # TODO(capture): the JSONPath to the answer text in that body.',
      '      text: $.TODO',
    ];
  }

  const patchLike = frames.some((frame) => {
    if (!frame.data) return false;
    try {
      const parsed = JSON.parse(frame.data) as Record<string, unknown>;
      return 'p' in parsed || 'v' in parsed;
    } catch {
      return false;
    }
  });

  if (patchLike) {
    return [
      '    stream:',
      '      # The frames carry {p, o, v} patch operations. Note that the path is',
      '      # sticky: a frame with no `p` continues the previous one.',
      '      format: json-patch',
      "      doneWhen: { data: '[DONE]' }",
      '      patch:',
      '        pathField: p',
      '        opField: o',
      '        valueField: v',
      '        # TODO(capture): which fragment type feeds which channel. Read the',
      '        #   recorded frames — the type names are in them.',
      '        routes: { RESPONSE: text, THINK: reasoning }',
    ];
  }

  const textPath = guessTextPath(frames.map((frame) => frame.data).filter(isString));
  return [
    '    stream:',
    '      format: sse',
    "      doneWhen: { data: '[DONE]' }",
    '      map:',
    textPath
      ? `        text: ${textPath}`
      : '        # TODO(capture): the JSONPath to the text delta inside a frame.\n        text: $.TODO',
  ];
}

/**
 * Finds a path that holds a growing string across frames.
 *
 * Only paths that appear in most frames and hold short strings qualify. An id that
 * happens to be a string in every frame would otherwise be proposed as the answer
 * text, and the resulting declaration would stream the same id forever.
 */
function guessTextPath(datas: readonly string[]): string | undefined {
  const counts = new Map<string, number>();
  let parsed = 0;

  for (const data of datas) {
    let frame: unknown;
    try {
      frame = JSON.parse(data);
    } catch {
      continue;
    }
    parsed += 1;
    for (const [path, value] of stringPaths(frame, '$', 0)) {
      if (value.length > 0 && value.length < 200) {
        counts.set(path, (counts.get(path) ?? 0) + 1);
      }
    }
  }

  if (parsed === 0) return undefined;
  const ranked = [...counts.entries()]
    .filter(([, count]) => count >= parsed * 0.5)
    .sort((a, b) => b[1] - a[1]);
  return ranked[0]?.[0];
}

function* stringPaths(node: unknown, path: string, depth: number): Iterable<[string, string]> {
  if (depth > 6) return;
  if (typeof node === 'string') {
    yield [path, node];
    return;
  }
  if (Array.isArray(node)) {
    for (const [index, item] of node.entries()) {
      yield* stringPaths(item, `${path}[${index}]`, depth + 1);
    }
    return;
  }
  if (node !== null && typeof node === 'object') {
    for (const [key, value] of Object.entries(node)) {
      yield* stringPaths(value, `${path}.${key}`, depth + 1);
    }
  }
}

function isString(value: string | undefined): value is string {
  return typeof value === 'string';
}

/** Headers identical on every flow request: fingerprint material, not step data. */
function staticHeaders(
  entries: readonly CaptureEntry[],
  flow: readonly AnalyzedStep[],
): HeaderPair[] {
  const requests = flow
    .map((step) => entries[step.index])
    .filter((entry): entry is CaptureEntry => entry !== undefined);
  if (requests.length === 0) return [];

  const first = requests[0] as CaptureEntry;
  const shared: HeaderPair[] = [];

  for (const [name, value] of first.request.headers) {
    const lower = name.toLowerCase();
    if (SKIP_HEADERS.has(lower) || isCredentialHeader(lower)) continue;
    if (requests.every((entry) => headerValue(entry.request.headers, lower) === value)) {
      shared.push([lower, value]);
    }
  }

  return shared.sort((a, b) => (a[0] < b[0] ? -1 : 1));
}

function perRequestHeaders(headers: readonly HeaderPair[]): HeaderPair[] {
  return headers
    .filter(([name]) => {
      const lower = name.toLowerCase();
      return !SKIP_HEADERS.has(lower) && !isCredentialHeader(lower);
    })
    .filter(([name]) => VOLATILE_HEADER_HINTS.some((hint) => name.toLowerCase().includes(hint)))
    .map(([name, value]) => [name.toLowerCase(), value] as HeaderPair);
}

function headerOrderOf(entries: readonly CaptureEntry[], index: number): string[] {
  const entry = entries[index];
  if (!entry) return [];
  return entry.request.headers
    .map(([name]) => name.toLowerCase())
    .filter((name) => !SKIP_HEADERS.has(name));
}

/** Headers the transport owns; a declaration that sets them fights its own client. */
const SKIP_HEADERS = new Set([
  'host',
  'content-length',
  'connection',
  'accept-encoding',
  'transfer-encoding',
  'te',
  'upgrade',
  'keep-alive',
  ':authority',
  ':method',
  ':path',
  ':scheme',
]);

/** Headers whose value plainly changes per request. */
const VOLATILE_HEADER_HINTS = ['request-id', 'trace', 'nonce', 'timestamp', 'signature', 'pow'];

function isCredentialHeader(name: string): boolean {
  return ['authorization', 'cookie', 'x-api-key', 'x-auth-token', 'x-session-token'].includes(name);
}

function authShape(entries: readonly CaptureEntry[]): {
  kind: string;
  headers: [string, string][];
} {
  const hasCookie = entries.some((entry) => headerValue(entry.request.headers, 'cookie'));
  const authorization = entries
    .map((entry) => headerValue(entry.request.headers, 'authorization'))
    .find((value) => value !== undefined);

  const headers: [string, string][] = [];
  if (authorization) {
    const scheme = authorization.split(' ')[0];
    headers.push(['authorization', `${scheme === authorization ? '' : `${scheme} `}{{auth.token}}`]);
  }
  if (hasCookie) headers.push(['cookie', '{{auth.cookieHeader}}']);

  if (authorization && hasCookie) return { kind: 'cookie+bearer', headers };
  if (authorization) return { kind: 'bearer', headers };
  if (hasCookie) return { kind: 'cookie', headers };
  return { kind: 'none', headers };
}

function commonBase(flow: readonly AnalyzedStep[]): string | undefined {
  const origins = new Set<string>();
  for (const step of flow) {
    const url = safeUrl(step.url);
    if (url) origins.add(url.origin);
  }
  return origins.size === 1 ? [...origins][0] : undefined;
}

function jsonPathFor(link: ValueLink): string {
  return link.sourcePath.startsWith('$') ? link.sourcePath : `$.${link.sourcePath}`;
}

/** A model name if one is plainly in a request body; never a guess at one. */
function modelHint(bundle: CaptureBundle): string | undefined {
  for (const entry of bundle.entries) {
    if (!entry.request.body) continue;
    try {
      const parsed = JSON.parse(entry.request.body) as Record<string, unknown>;
      for (const key of ['model', 'model_type', 'model_name', 'modelId']) {
        const value = parsed[key];
        if (typeof value === 'string' && value !== '') return value;
      }
    } catch {
      continue;
    }
  }
  return undefined;
}

/** The last request whose JSON body holds a field a prompt would live in. */
function inferSendStep(
  flow: readonly AnalyzedStep[],
  entries: readonly CaptureEntry[],
): AnalyzedStep | undefined {
  for (const step of [...flow].reverse()) {
    const entry = entries[step.index];
    if (!entry?.request.body) continue;
    try {
      const parsed = JSON.parse(entry.request.body) as Record<string, unknown>;
      if (Object.keys(parsed).some((key) => isPromptKey(key))) return step;
    } catch {
      // A form-encoded body counts too: the field names are still readable.
      if (/(^|&)(prompt|message|text|query|input|content)=/.test(entry.request.body)) return step;
    }
  }
  return undefined;
}

function firstOrigin(flow: readonly AnalyzedStep[]): string | undefined {
  for (const step of flow) {
    const url = safeUrl(step.url);
    if (url) return url.origin;
  }
  return undefined;
}

/**
 * Describes a value without reproducing it.
 *
 * A per-request header can hold a signature or an encoded credential. The reader needs
 * to know its shape to pick a transform; they do not need the value, and a draft is a
 * file people paste into issues.
 */
function describeValue(value: string): string {
  const kind = /^[A-Za-z0-9+/]+=*$/.test(value) && value.length > 24
    ? 'base64'
    : /^[0-9a-f]{16,}$/i.test(value)
      ? 'hex'
      : /^\d+$/.test(value)
        ? 'digits'
        : 'text';
  return `${kind}, ${value.length} characters`;
}

function safeUrl(url: string): URL | undefined {
  try {
    return new URL(url);
  } catch {
    return undefined;
  }
}

/**
 * Single-quoted YAML unless the value is plainly safe bare.
 *
 * "Safe" excludes anything YAML would read as another type. A header value like
 * `20241129.1` is a string to HTTP and a float to YAML, and the difference surfaces as
 * a schema error on a file the drafter itself produced.
 */
function quote(value: string): string {
  const bareSafe = /^[A-Za-z0-9._/\-]+$/.test(value);
  const readsAsOtherType =
    /^(true|false|null|yes|no|on|off|~)$/i.test(value) ||
    /^[+-]?(\d[\d_]*(\.\d*)?|\.\d+)([eE][+-]?\d+)?$/.test(value) ||
    /^0[xob]/i.test(value);
  return bareSafe && !readsAsOtherType ? value : `'${value.replace(/'/g, "''")}'`;
}
